server {
  listen 80;
  server_name _;
  location /api/analytics/ { proxy_pass http://analytics:8080/; proxy_set_header Host $host; }
  location /api/generator/ { proxy_pass http://generator:8080/; proxy_set_header Host $host; }
  location / { proxy_pass http://web:80; }
}
